version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo/project

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: ./selenoid_start.sh
      - run: docker ps
      - run: ./gradlew clean test