version: 2
jobs:
  build:
    machine: true
    java:
      version: oraclejdk8

    working_directory: ~/repo/project

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Start up Selenoid environment
          command: ./selenoid_start.sh

      - run:
          name: Run tests
          command: ./gradlew clean test

      - run:
          name: Generate Allure report
          command: ./gradlew allureReport

      - store_test_results:
          path: ./build/test-results

      - store_artifacts:
          path: ./build/reports/allure-report