version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker:
         version: 19.03.12
      - run: echo "$DOCKER_HOST"
      - run: ./selenoid_start.sh
      - run: docker ps
      - run: ./gradlew clean test