version: 2
jobs:
  build:
    machine: true
    java:
      version: oraclejdk8

    working_directory: ~/repo/project

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: ./selenoid_start.sh

      - run: ./gradlew clean test && ./gradlew allureReport

      - store_artifacts:
         path: ./build/reports/allure-report