version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker:
         version: 19.03.12
      - run: ./selenoid_start.sh && sleep 100
      - run: docker ps
      - run:
         name: Check selenoid
         command: curl http://127.0.0.1:4444/status
         when: always
      - run: ./gradlew clean test